id: I6119C9E4
legacy_id: null
ocr_import_info:
  bdrc_scan_id: W23468
  source: bdrc.io
  batch_id: batch003
  software_id: vision
  expected_default_language: bo
  ocr_info: {}
  op_import_options: {}
  op_import_version: 0.9.7
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-11-01T09:29:43.647510+00:00'
last_modified: '2022-11-01T09:29:43.647516+00:00'
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W23468
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23468
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མི་ཕམ་རྒྱ་མཚོ།
  languages:
  - bo
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9646019480692255
  ocr_word_median_confidence_index: 0.998306665
quality: null
bases:
  I2004:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2004
      total_pages: 859
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I2004.txt
    statistics:
      ocr_word_median_confidence_index: 0.998306665
      ocr_word_mean_confidence_index: 0.9646019480692255
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
